# Generated by Django 2.2.4 on 2019-08-08 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_sn', models.CharField(default=False, max_length=50, verbose_name='商品编号')),
                ('old_sn', models.CharField(default=False, max_length=50, verbose_name='原厂编号')),
                ('name', models.CharField(default=False, max_length=30, verbose_name='商品名')),
                ('shop_price', models.FloatField(default=0, verbose_name='本店价格')),
                ('buy_num', models.IntegerField(default=0, verbose_name='购买数量')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('goods_num', models.IntegerField(default=0, verbose_name='库存数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类目')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
    ]
