# Generated by Django 2.2.4 on 2019-08-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goods_goods_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='old_sn',
            field=models.CharField(default='', max_length=50, verbose_name='原厂编号'),
        ),
    ]
