# Generated by Django 2.2.4 on 2019-08-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190808_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='封面图'),
        ),
    ]
