# Generated by Django 2.2.4 on 2019-08-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='namephoto',
            field=models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='用户头像'),
        ),
    ]
