# Generated by Django 2.2.4 on 2019-08-12 11:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='', max_length=30, verbose_name='省份')),
                ('city', models.CharField(default='', max_length=20, verbose_name='城市')),
                ('district', models.CharField(default='', max_length=30, verbose_name='区域')),
                ('street', models.CharField(default='', max_length=30, verbose_name='街道')),
                ('address', models.CharField(default='', max_length=60, verbose_name='详细地址')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='手机号码')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收货地址',
                'verbose_name_plural': '收货地址',
            },
        ),
    ]
