# Generated by Django 2.2.4 on 2019-08-12 15:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIntegrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integrate_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='订单时间')),
                ('source', models.CharField(default='', max_length=50, verbose_name='来源')),
                ('expiry_day', models.CharField(default='', max_length=12, verbose_name='有效期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '我的积分',
                'verbose_name_plural': '我的积分',
            },
        ),
    ]
