# Generated by Django 2.2.4 on 2019-08-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0004_usermessage_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='upload_file',
            field=models.FileField(upload_to='goods/images/', verbose_name='上传文件'),
        ),
    ]
