# Generated by Django 2.2.4 on 2019-08-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0005_auto_20190819_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='content',
            field=models.TextField(default='', max_length=500, verbose_name='留言内容'),
        ),
    ]
