# Generated by Django 2.2.4 on 2019-08-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0007_auto_20190819_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='upload_file',
            field=models.FileField(upload_to='messages/images/', verbose_name='上传文件'),
        ),
    ]
