# Generated by Django 2.2.4 on 2019-08-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0008_auto_20190819_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='upload_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='usermessage',
            old_name='content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='usermessage',
            old_name='title',
            new_name='subject',
        ),
    ]
