# Generated by Django 2.2.4 on 2019-08-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0010_auto_20190819_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='file',
            new_name='upload_file',
        ),
    ]
