# Generated by Django 2.2.4 on 2019-08-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0011_auto_20190819_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='upload_file',
            new_name='file',
        ),
    ]
